name: hw-json-demo
version: '0.1.0.0'
synopsis: Demo library
description: Please see README.md
category: Data, Conduit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-json-demo
homepage: http://github.com/haskell-works/hw-json#readme
extra-source-files:
- README.md
ghc-options:
- -Wall
- -O2
- -msse4.2
dependencies:
- base >=4 && <5
- aeson
- array
- attoparsec
- bytestring
- conduit
- containers
- deepseq
- dlist
- hw-bits
- hw-conduit
- hw-excess >=0.0.0.1
- hw-json >=0.4.0.0
- hw-json-mquery
- hw-mquery >=0.1.0.1
- hw-diagnostics
- hw-parser
- hw-prim >=0.4.0.0
- hw-rankselect >=0.5.0.0
- hw-rankselect-base >=0.1.0.0
- mmap
- mono-traversable
- resourcet
- text
- vector
- word8
library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Data.Json.Demo
